### ISSUE TITLE
[Docs improvement]

### ISSUE THREAD

**Issue by Mister-Hope** [cunyu1943/JavaPark#16]
Spending some times checking your docs, here are some suggestions.

## Never use deprecated tags

Tags like `<center>` are already deprecated and being removed in HTML5. In markdown with `align: true`, you can use:

```md
::: center

contents

:::
```

to achieve this.

## Attrs and image size support

with `attrs: true` and `imgSize: true`, `<img src="/personal/wechat.png" alt="微信群" width="150" style="zoom: 70%“ />` can be wriiten as:

```md
![微信群](/personal/wechat.png =150x) {style=zoom:70%}
```

## Use relative links in markdown or absolute links when img is in public

You should never use relative path to reference public images as contents in that folder will be copied to dest folder. By doing this, two copies of the same image will be in the final production.

To make better writting, place markdown images next to markdown (e.g.: in a fodler named `assets`). then use `./assets/image-name.png` to reference it.

## Do not enable markdown enhance features you do not use

Enabling all features will slow down render speed, increase build memory usage and largen output size.

## Do not place raw text in tex equations

In tex when you want to render a text `XXX`, you should use `\text{XXX}`

**Comment by cunyu1943** [comment]
Thans for your sugguestions!

**Comment by cunyu1943** [comment]
> Spending some times checking your docs, here are some suggestions.
> 
> ## Never use deprecated tags
> Tags like `<center>` are already deprecated and being removed in HTML5. In markdown with `align: true`, you can use:
> 
> ```lisp
> ::: center
> 
> contents
> 
> :::
> ```
> 
> to achieve this.
> 
> ## Attrs and image size support
> with `attrs: true` and `imgSize: true`, `<img src="/personal/wechat.png" alt="微信群" width="150" style="zoom: 70%“ />` can be wriiten as:
> 
> ```lisp
> ![微信群](/personal/wechat.png =150x) {style=zoom:70%}
> ```
> 
> ## Use relative links in markdown or absolute links when img is in public
> You should never use relative path to reference public images as contents in that folder will be copied to dest folder. By doing this, two copies of the same image will be in the final production.
> 
> To make better writting, place markdown images next to markdown (e.g.: in a fodler named `assets`). then use `./assets/image-name.png` to reference it.
> 
> ## Do not enable markdown enhance features you do not use
> Enabling all features will slow down render speed, increase build memory usage and largen output size.
> 
> ## Do not place raw text in tex equations
> In tex when you want to render a text `XXX`, you should use `\text{XXX}`

Thans for your sugguestions!

**Comment by Mister-Hope** [comment]
Also, it's not recommended to install a large site as PWA, as the update time can take longer then expected.

**Comment by cunyu1943** [comment]
> Also, it's not recommended to install a large site as PWA, as the update time can take longer then expected.

👌
